### ISSUE TITLE
add a 'title' configuration to better name alerts

### ISSUE THREAD

**Issue by chook** [joshgummersall/statsd-alerting-backend#10]
Today all statsd-alerting-backend are named the same. either
"metrics alert" or "event alert" which is not the best experience.

Small sample:
```
'title': 'Metric ${name} is misbehaving' 
```

Another sample:
```
'title': '${name} alert - ${metric} >= ${threshold}"

**Comment by joshgummersall** [comment]
I've got some experience working with [handlebars.js](http://handlebarsjs.com/) for templating, it seems pretty good for stuff like this. If you are planning to implement this feature, I'd suggest starting there!

**Comment by joshgummersall** [comment]
@chook I'm actually almost done with this, hopefully it's not something you spent a lot of time on.

**Comment by chook** [comment]
no i actually haven't done anything with the repo today. looking forward! :)

**Comment by joshgummersall** [comment]
@chook you can test out the feature here: https://github.com/joshgummersall/statsd-alerting-backend/tree/feat-handlebars-templating

To use a template for a given dispatcher, add the following to your dispatcher configuration:

```
{
  ...
  "template": "{{name}} event {{metric}}",
  "metricTemplate": "{{name}} metric event {{metric}}"
  ...
}
```
