### ISSUE TITLE
Where does the alerts config go.

### ISSUE THREAD

**Issue by osmancis** [joshgummersall/statsd-alerting-backend#13]
I added the hipchat configuration in config.js with in my statsd installation folder. This is the error I see -

z001v9s ~/statsd (master) $  node stats.js config.js
27 Jul 10:53:48 - [16456] reading config file: config.js
undefined:126
 alerts: {
 ^^^^^^

Ay idea or help is appreciated.

**Comment by joshgummersall** [comment]
A gist with your config.js file would be very helpful if you don't mind including that.

**Comment by osmancis** [comment]
Never mind, my configuration with hipchat doesn't seems to work. let me give the config.js settings I have for statsd server - 

alerts: {
    dispatchers: {
    hipchatDispatcher: {
        type: "hipchat",
        config: {
          key: "<KEY>",
          //from: "XYZ",
          room: "ABC",
          color: "red",
          notify: true,
          //template: "Saw some event!"
        }
    },
    events: [{
      name: "my.metric", //any metric fired matching this pattern will be sent out as an alert
      dispatcher: "hipchatDispatcher" //the service to which it will be reported
    }],
    metrics: [{
      name: "my.metric", //name of the metric
      type: "counters",
      gt: 0.00000001, //operator: gte, gt, lte, lt, eq, delta, delta_gte, delta_gt, delta_lte, delta_lt, delta_eq //delta is the difference between the current sample and the previous one
      dispatcher: "hipchatDispatcher" //the service (e.g,PagerDuty) to which this alert is sent.
    }]
  }

**Comment by osmancis** [comment]
Also, can I see logs to find whats going on behind the screen when I am trying to send messages to hipchat?

**Comment by joshgummersall** [comment]
There is no debug logging currently in place so you would have to meander in the `node_modules` directory and add some logging yourself. I don't see anything immediately wrong with your configuration file so I would urge you to keep playing with it. Maybe the stats aren't being emitted properly by your application?
