### ISSUE TITLE
Integration with HipChat

### ISSUE THREAD

**Issue by chook** [joshgummersall/statsd-alerting-backend#6]
Pretty much same as Slack.

**Comment by joshgummersall** [comment]
@chook I noticed you forked the repository, is this something you are going to be implementing or is this a feature request?

**Comment by chook** [comment]
If you won't do it this week I'll probably do it in the next one :)

**Comment by joshgummersall** [comment]
If I get some time in a few days I'll knock this out, otherwise feel free to submit a PR and I'll review.

**Comment by mpayetta** [comment]
@joshgummersall @chook I've just created a pull request with this feature :)

**Comment by joshgummersall** [comment]
@chook - just published v0.1.3 that includes @mpayetta's hipchat alert backend.

**Comment by joshgummersall** [comment]
@chook - actually I'd suggest using v0.1.4 - I found a small issue that I fixed and created a new release.

**Comment by chook** [comment]
awesome! thanks!
